Fix symbolic link, salt_solo.rb and bash if statements
saltstack/kitchen-salt pull request #111
Opened 2017-06-26 01:35 UTC by arif-ali

* add fi at end of the if for the salt_solo.rb
* update the if statement from previous commit, to look similar to previous statements in salt_solo.rb
* Test to see if the file exists for gem and ruby, rather than forcing the symbolic link, otherwise it shows a warning
* exit with exit 0 in the install.sh by default. This then doesn't fail the `salt-call`

This is a further fix for #107, after testing #110

2017-06-26 01:39 UTC, arif-ali commented
@gtmanfred, thanks for accepting the previous PR, but there was still a typo in the salt_solo.rb, and the exit 0 issues.

The symbolic link tests were added as a nice to have, so that we don't get the warning

I made sure to test this manually, by updating the scripts manually in the gems and the kitchen docker images, and at least it now goes past the main issue I had.

Apologies for not thoroughly testing it previously

2017-06-26 15:34 UTC, gtmanfred commented
@arif-ali can you rebase this?

Thanks!
Daniel

2017-06-26 20:27 UTC, arif-ali commented
Damn, it was rebased when, I committed. I think one of the issues fixed. 

I will update the commit, after I rebased, and see if any of the fixed issues have already been done

2017-06-27 14:59 UTC, arif-ali commented
@gtmanfred, I have rebased it ;)

2017-06-27 15:20 UTC, gtmanfred requested changes
One small change if you wouldn't mind getting that, and then I will merge the changes.

Thanks!
Daniel

2017-06-27 15:20 UTC, gtmanfred commented on assets/install.sh
> +  [[ ! -e /opt/chef/embedded/bin/ruby ]] && ln -sf `which ruby` /opt/chef/embedded/bin/
If we are going to check if the link exists first, then we don't need the `-f` here.

2017-06-27 15:36 UTC, arif-ali commented on assets/install.sh
> +  [[ ! -e /opt/chef/embedded/bin/ruby ]] && ln -sf `which ruby` /opt/chef/embedded/bin/
yeah, sure, I am happy with that

2017-06-27 15:48 UTC, gtmanfred approved these changes

2017-06-27 15:48 UTC, merged