Added Salt Yum Repo Configuration
saltstack/kitchen-salt pull request #131
Opened 2017-08-04 00:51 UTC by dennisfoconnor

I needed to change the yum repo, so I could install it using the salt-stack yum like we do on our production servers. I replicated the configuration for the apt installs.

The version check was failing when tying installation to a minor version i.e. 2016.11.5 was failing because it was comparing to 2016.11. I added full version comparison in addition to the short version comparison.

2017-08-07 21:51 UTC, gtmanfred commented on .gitignore
> +.vscode
this needs a newline after it

2017-08-07 21:57 UTC, gtmanfred requested changes
Some things need to be changed in this.

We should be looking up the el version for the defaults.

2017-08-07 21:57 UTC, gtmanfred commented on .gitignore
> +.vscode
This needs a newline

2017-08-07 21:57 UTC, gtmanfred commented on lib/kitchen/provisioner/salt_solo.rb
> +        salt_yum_repo_latest: 'https://repo.saltstack.com/yum/redhat/salt-repo-latest-2.el7.noarch.rpm'
This needs some logic to make sure that it grabs the correct rpm for each redhat version.  Not always el7.

2017-08-07 21:57 UTC, gtmanfred commented on lib/kitchen/provisioner/salt_solo.rb
> +        salt_yum_rpm_key: 'https://repo.saltstack.com/yum/redhat/7/x86_64/archive/%s/SALTSTACK-GPG-KEY.pub',
shouldn't also template the redhat version here

2017-08-07 21:57 UTC, gtmanfred commented on provisioner_options.md
> +salt_yum_rpm_key | https://repo.saltstack.com/yum/redhat/7/x86_64/archive/%s/SALTSTACK-GPG-KEY.pub" | The uri to the public key imported using rpm before adding the yum repo. `%s` is replaced with sa
this shouldn't be 7 either.

2017-08-07 21:57 UTC, gtmanfred commented on provisioner_options.md
> +salt_yum_repo_latest | https://repo.saltstack.com/yum/redhat/salt-repo-latest-2.el7.noarch.rpm" | The uri to the rpm file for the latest version of salt. Used to install if salt_version is latest. Fo
same here

2017-08-07 21:57 UTC, gtmanfred commented on spec/kitchen/provisioner/salt_solo_spec.rb
> +  let(:salt_yum_rpm_key) { 'https://repo.saltstack.com/yum/redhat/7/x86_64/archive/%s/SALTSTACK-GPG-KEY.pub'}
same

2017-08-07 21:57 UTC, gtmanfred commented on spec/kitchen/provisioner/salt_solo_spec.rb
> +  let(:salt_yum_repo_latest) { 'https://repo.saltstack.com/yum/redhat/salt-repo-latest-2.el7.noarch.rpm' }
same

2017-08-10 16:31 UTC, epcim commented on lib/kitchen/provisioner/salt_solo.rb
> +        salt_yum_repo_latest: 'https://repo.saltstack.com/yum/redhat/salt-repo-latest-2.el7.noarch.rpm'
override on kitchen config. Assume these are default (for latest).

2017-08-19 01:19 UTC, gtmanfred commented on lib/kitchen/provisioner/salt_solo.rb
> +        salt_yum_repo_latest: 'https://repo.saltstack.com/yum/redhat/salt-repo-latest-2.el7.noarch.rpm'
that is fair.

2017-08-19 02:18 UTC, gtmanfred approved these changes

2017-08-19 02:48 UTC, merged