ADD Devuan support
saltstack/kitchen-salt pull request #171
Opened 2017-11-12 13:44 UTC by ymasson

2017-11-12 18:31 UTC, gtmanfred requested changes

2017-11-12 18:31 UTC, gtmanfred commented on assets/install_with_git.sh
> +elif test -f "/etc/devuan_version"; then
I would rather have this on the previous line and just have an or statement.

2017-11-12 20:40 UTC, gtmanfred approved these changes

2017-11-12 20:41 UTC, merged

2017-11-12 22:11 UTC, ymasson commented
Thanks

2017-11-13 00:00 UTC, gtmanfred commented
No problem, I am working in revamping the documentation, once that is done
I will make a release with this in it.

On Sun, Nov 12, 2017, 3:11 PM Yann Masson <notifications@github.com> wrote:

> Thanks
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/saltstack/kitchen-salt/pull/171#issuecomment-343772302>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAssoWculy2BNDSQC7oTaubMYdb-KU3Pks5s12z4gaJpZM4Qa4nW>
> .
>