Add assets support for FreeBSD
saltstack/kitchen-salt pull request #255
Opened 2018-09-10 21:33 UTC by amontalban

Currently the assets scripts are not working with FreeBSD, so I'm adding support for it.

2018-09-11 15:24 UTC, rickh563 commented
ZD-2825

2018-09-24 12:32 UTC, gtmanfred requested changes
this looks good, just some small change requests

2018-09-24 12:32 UTC, gtmanfred commented on assets/install.sh
> +os=`uname -s`
This should be a subshell, and not backtics

`os="$(uname -s)"

2018-09-24 12:32 UTC, gtmanfred commented on assets/install_with_git.sh
> +os=`uname -s`
same here

2018-09-24 12:51 UTC, amontalban commented
@gtmanfred pushed.

PS: Do you want me to do a PR to remove the other backtics in this scripts?

2018-09-24 12:53 UTC, gtmanfred commented
It also needs to be quoted, to incase of expansion.

Also yes, that would be great if you could remove the other backtics!

I haven't had time to go through and clean up all the asset scripts, but the added tests are here if you want to start with these shellcheck commands https://github.com/saltstack/kitchen-salt/pull/160

2018-09-24 13:33 UTC, amontalban commented
@gtmanfred cool, I will do a PR to fix #160 then. If you can merge this now would be great. Thanks!

2018-09-24 13:34 UTC, gtmanfred approved these changes

2018-09-24 13:35 UTC, merged