Allow the `salt-call` command execution to be bypassed
saltstack/kitchen-salt pull request #278
Opened 2019-02-12 16:28 UTC by s0undt3ch

2019-02-12 16:44 UTC, gtmanfred requested changes

2019-02-12 16:44 UTC, gtmanfred commented on lib/kitchen/provisioner/salt_solo.rb
> +        return unless config[:run_salt_call]
Can you add this to the documentation pages?

2019-02-12 16:47 UTC, s0undt3ch commented
There. Is that enough?

2019-02-12 17:01 UTC, gtmanfred approved these changes
perfect!

2019-02-13 13:32 UTC, daks commented
What is the use case of not running salt-call inside a Kitchen VM?

I think Kitchen can be configured to not have a provisioner, if you only want to kitchen create and kitchen verify. _(but I may be wrong)_

2019-02-13 13:36 UTC, s0undt3ch commented
We're in the process of creating "golden" images, which means, we previously ran the salt states against the VM, which makes this step unnecessary.

2019-02-13 14:50 UTC, gtmanfred commented
There are still other stuff in the kitchen-salt stuff that is being used (specifically to transport the salt repo over to the testing instance).

2019-02-13 14:50 UTC, merged

2019-02-13 14:53 UTC, gtmanfred commented
v0.5.0 released with your recent additions @s0undt3ch

2019-02-13 15:11 UTC, s0undt3ch commented
Thanks!

2019-02-13 16:35 UTC, daks commented
@s0undt3ch We use golden images too, but we create Vagrant images and don't use these images with Kitchen.