Fix for Amazon Linux Images
saltstack/kitchen-salt pull request #287
Opened 2019-04-17 01:22 UTC by nshenry03

Specifically `amazonlinux:2` from https://hub.docker.com/_/amazonlinux

2019-04-19 18:25 UTC, gtmanfred requested changes

2019-04-19 18:25 UTC, gtmanfred commented on assets/install.sh
> +  platform="$(sed 's/^\(.\+\) release.\+/\1/' /etc/system-release | awk '{print $1}' | tr '[:upper:]' '[:lower:]')"
Can this just be changed to only an awk command?

2020-12-05 02:28 UTC, bryceml commented
Duplicate of https://github.com/saltstack/kitchen-salt/pull/319

2020-12-13 03:07 UTC, s0undt3ch commented
A fix is now merge which fixes this. Closing.

2020-12-13 03:07 UTC, closed without merging