new pre_salt_command
saltstack/kitchen-salt pull request #297
Opened 2019-12-10 08:34 UTC by daks

Hello,

this is an intent to solve #295 implementing a new directive `pre_salt_command` which lets the user define a command to run just before `salt-call` but after salt installation and files copying.

I'm not fluent in Ruby dev so this is my raw intent but it may need some advices for a better implementation or adding tests.

2019-12-10 15:01 UTC, gtmanfred requested changes
I believe this already exists with what I mentioned here. https://github.com/saltstack/kitchen-salt/issues/295#issuecomment-564072809

2019-12-13 15:55 UTC, daks commented
The solution given don't solve my problem, so I think this PR can be useful. Can someone look at it?

2019-12-18 14:09 UTC, s0undt3ch approved these changes

2019-12-18 14:09 UTC, s0undt3ch commented
Could you pleased rebase and sign your commits?

2019-12-30 13:52 UTC, daks commented
@s0undt3ch GPG signing done

2020-01-02 08:49 UTC, s0undt3ch approved these changes

2020-01-02 08:49 UTC, merged

2020-01-02 08:49 UTC, s0undt3ch commented
Thank You!

2020-01-02 09:39 UTC, daks commented
Thank you for the merge.

2020-01-13 19:27 UTC, n-rodriguez commented on lib/kitchen/provisioner/salt_solo.rb
> +          cmd << "#{config[:pre_salt_command]};"
Using post condition would have been more consistent.