Windows support
saltstack/kitchen-salt pull request #74
Opened 2016-11-04 13:31 UTC by lomeroe

Adding windows support to refactored kitchen-salt code.

2017-06-07 18:28 UTC, gtmanfred commented
@lomeroe is it ok with you if we get #50 in first, and then if there are any more changes that need to be made, we can make them after that?

Thanks,
Daniel

2017-06-08 20:12 UTC, lomeroe commented
I will take a look at it, been quite a while since I created it...I can't remember why I did my own PR instead of using #50 

I'm excited to see that saltstack has taken kitchen-salt on.

2017-06-09 00:32 UTC, gtmanfred commented
I am excited too, though i have been really struggling and need to brush up on my ruby 😸

2017-06-09 14:33 UTC, lomeroe commented
@gtmanfred I poked through this and it looks like the differences are:

1) I don't hard code c:\tmp as the temp directory, I use $env:Temp
2) I use a erb template for the windows minion install
3) salt-call command's retcode is returned/tested
4) I didn't add any tests

Not sure why I didn't just take that PR and make updates to it, looks like I "borrowed" some that PR's code.  Likely b/c of my weak git fu.

2017-06-09 15:07 UTC, barkingfoodog commented
1. This makes plenty of sense, so I'm all for it
2. I've worked on re-basing #50 last night and noticed the shift to using `.erb` files. It makes sense to move the main installation script out to a separate file, so +1 for this item as well
3. Good deal. This was a TODO item I'd left in #50 
4. These would be pretty easy to port over

In short, I think we need to standardize on one of these PRs, since #74 doesn't really build on #50 in terms of the commit history. I'm cool to go with this one and can port over the tests if you'd like. They most make sure the scripts quack like a duck on unix and honk like a goose on Windows. ;)

I also noticed you're using the official `salt_bootstrap.ps1` script instead of chocolately, which is also just fine by me.

2017-06-09 15:15 UTC, gtmanfred commented
Yeah, i like the ps1 script instead of chocolately too.

So if you could rebase this @lomeroe and the @barkingfooddog if you could port over the tests once we get this merged, i would appreciate it!

I am going to close #50 then.

Thanks

2017-06-09 15:23 UTC, barkingfoodog commented
@gtmanfred will do. I'll watch for this to be merged and make a separate PR with the tests.

2017-06-13 21:48 UTC, lomeroe commented
I still need to test this after the rebase, but wanted to put it up here so others could test as well...

2017-06-14 18:19 UTC, lomeroe commented
@gtmanfred this tested out on my end...

2017-06-14 18:34 UTC, gtmanfred requested changes
Just one nitpicky thing and a question about another, and then it should be good to merge.

2017-06-14 18:34 UTC, gtmanfred commented on Gemfile
> +# vi: set ft=ruby :
Can you fix this and add the newline at the end of the file back?

2017-06-14 18:34 UTC, gtmanfred commented on lib/kitchen/provisioner/salt_solo.rb
> +          cmd = "rm ""#{config[:root_path]}"" -Recurse -Force; mkdir -Path ""#{config[:root_path]}"
Does this really need to be recursively removed first?

2017-06-14 18:55 UTC, gtmanfred commented
Would you also double check that the changes made here also work on windows?
https://github.com/saltstack/kitchen-salt/pull/72/files

Thanks
Daniel

2017-06-14 19:04 UTC, lomeroe commented on Gemfile
> +# vi: set ft=ruby :
oops, sure

2017-06-14 19:05 UTC, lomeroe commented on lib/kitchen/provisioner/salt_solo.rb
> +          cmd = "rm ""#{config[:root_path]}"" -Recurse -Force; mkdir -Path ""#{config[:root_path]}"
I can remove it so it is like the non-windows side, the root_path directory was originally recursively cleaned out for non-windows, but I did notice the change on that one while rebasing (I honestly don't have any thoughts either way if it needs to be done or not)

2017-06-14 19:06 UTC, gtmanfred commented on lib/kitchen/provisioner/salt_solo.rb
> +          cmd = "rm ""#{config[:root_path]}"" -Recurse -Force; mkdir -Path ""#{config[:root_path]}"
I would say for now lets make them the same.

2017-06-14 20:02 UTC, gtmanfred approved these changes

2017-06-14 20:04 UTC, merged

2017-06-14 20:04 UTC, gtmanfred commented
alright, @barkingfoodog you are up

2017-06-14 20:16 UTC, lomeroe commented
My config still works w/#72 merged, but I specify pillars in the .kitchen.yml and have is_file_roots set to true.  I don't *see* anything that makes me think it wouldn't work, but I will admit my brain is a little mushy right now and trying to figure out what all is going on there/intended, so I could test other scenarios, is not going well for me...

2017-06-14 20:20 UTC, gtmanfred commented
Yeah, no worries, I am going to take care of it once we have tests for windows.

2017-06-14 20:20 UTC, gtmanfred commented
Thanks for the help!

2017-06-14 20:20 UTC, barkingfoodog commented
@gtmanfred will do!